site_name: Graft.jl
site_description: Graph Toolkit for Julia
repo_url: https://github.com/pranavtbhat/Graft.jl

theme: material

extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- [index.md, Introduction]
- [generator.md, Generation, Graph API]
- [combinatorial.md, Combinatorial, Graph API]
- [mutation.md, Mutation, Graph API]
- [labelling.md, Labelling, Graph API]
- [vdata.md, Vertex Metadata, Metadata]
- [edata.md, Edge Metadata, Metadata]
- [queries.md, Query Macro, Query API]
- [hopgraph.md, Hop Subgraphs, Query API]
- [graphio.md, File IO, Graph IO]
- [export.md, Export, Graph IO]
- [edgeiter.md, Edge Iteration, Internal]
- [internal.md, Internal Docs, Internal]
